### Home
GET http://localhost:8000

### Create Department
POST http://localhost:8000/departments
Content-Type: application/json

{
  "name": "Finance",
  "staff_count": 3
}

### List Departments
GET http://localhost:8000/departments